name: BMI_Hello

# trigger workflow on push to master i.e. a commit is pushed to a branch, or pull request with master as base

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]              # branch names optional

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build", jobs can run in parallel
  hello:
    # The type of runner that the job will run on e.g. windows-latest, macos-latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world BMI!
